services:
  blitzkrieg:
    image: kajune/blitzkrieg:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    working_dir: /app/backend
    command: python3 app.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "5000:5000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      POSTGRES_HOST: "host.docker.internal"
